In [0]:
import numpy as np
a = [x for x in np.arange(100) if x%2 == 0]

In [12]:
print(a)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


In [0]:
def countAlphabets(str):
  dict = {}
  for alpha in str:
    dict[alpha] = dict[alpha] + 1 if alpha in dict.keys() else 1
  print(dict)

In [24]:
countAlphabets('missiisippi')
print(dict)

{'m': 1, 'i': 5, 's': 3, 'p': 2}
<class 'dict'>


In [0]:
zeros = np.zeros(10)

In [27]:
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [35]:
full_matrix = np.full((3,3),1)
full_matrix

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [45]:
full_matrix[0]
full_matrix[0] = np.arange(3)
full_matrix[1] = np.arange(3,6)
full_matrix[2] = np.arange(6,9)
full_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
full_matrix = full_matrix * 3
full_matrix

array([[ 0,  9, 18],
       [27, 36, 45],
       [54, 63, 72]])

In [60]:
mat1 = np.matrix([[1, 4],[2, 5],[3, 6]])
mat2 = np.matrix([[1, 0],[0, 1],[0, 0]])
mat3 = mat1.T.dot(mat2)
mat3

matrix([[1, 2],
        [4, 5]])

In [61]:
mat3 = mat3 + np.array([-1, 1])
mat3

matrix([[0, 3],
        [3, 6]])

In [70]:
X = np.random.rand(3,3)
X

array([[0.693316  , 0.4527693 , 0.98122993],
       [0.48241945, 0.28032566, 0.83779964],
       [0.52229995, 0.53879821, 0.67290344]])

In [71]:
test = X > 0.5
test

array([[ True, False,  True],
       [False, False,  True],
       [ True,  True,  True]])

In [76]:
X[test] = -1
X

array([[-1.        ,  0.4527693 , -1.        ],
       [ 0.48241945,  0.28032566, -1.        ],
       [-1.        , -1.        , -1.        ]])

In [0]:
import imageio
im = imageio.imread('imageio:chelsea.png')

In [79]:
im.shape
im.

(300, 451, 3)